### ISSUE TITLE
Troubles with the installation

### ISSUE THREAD

**Issue by ViolentVio** [limtis0/SkulPatcher#2]
Hi, this mod is not working for me I don't think. Skul is updated, I followed the 4 steps but when I launched the game and went into it nothing special happened. F7 doesn't do anything either. Am I just missing something to like activate the mod or did I mess up in one of the 4 steps is basically my question. The only step that I had to deviate was step 4, as there was no "plugins" folder in "BepInEx" so I made one and placed "SkulPatcher.dll" in there. I tried with both bepinex x64 and x86, with v2.3 and v2.2 of skulpatcher itself, but I don't even really know what I'm looking for here

**Comment by Catpoleon** [comment]
First, thanks limtis0 for this mod! Awesome! I just wanted something that let me get too many items. I beat the game and now wanted to play with being OP on a slow build-up. Amazing work here!

For installation, ViolentVio, I trialed and errored some and came up with this, which has worked for me:

"$(SkulDirectory)" is the game folder. For Steam, it's probably something like: C:\Program Files (x86)\Steam\steamapps\common\Skul

1. Extract Unity files 2020.3.34 (just the files, not the folder) into $(SkulDirectory)\Skul_Data\Managed\
- This may require approving overwriting some files

2. Extract corelibs 2020.3.34 files (just the files, not the folder) into $(SkulDirectory)\Skul_Data\Managed\
- This may require approving overwriting some files

3. Extract BepInEx 5.4.21 (just the one zip file, no source code files) into $(SkulDirectory). This should create a BepInEx subdirectory under $(SkulDirectory) AND put three files directly in your $(SkulDirectory) (i.e. changelog, doorstop_config, and winhttp.dll).

4. Extract the .dll mod file into $(SkulDirectory)\BepInEx\plugins (again, without any folder from the unzipping; the .dll file should be directly in the plugins subfolder)

Run the game. Press F7 to bring up the mod menu.

(I did not edit the doorstop_config file. I believe that and limtis0 having you create a subfolder for steps 1&2 was to allow you to easily revert back to the original game unmoded. Though I could be wrong. But you can uninstall from Steam and delete the files, then re-install if you want to remove the mod.)

I hope that works for you!

**Comment by limtis0** [comment]
@Catpoleon thank you for the feedback and for the provided answer, it sums pretty much everything :)

As you've said, I've added the steps of creating a `2020.3.34` folder and editing the `doorstop.ini` just for future-proofing and ease of deletion. These steps are not obligatory and you can easily extract all of the Unity/Corelibs files into `$(SkulDirectory)\Skul_Data\Managed\`

One more thing: if you still have some issues, you can set `[Logging.Console] Enabled = true` in `$(SkulDirectory)\BepInEx\config\BepInEx.cfg` and it will provide you with some more data to clarify what the actual problem is.

If you don't have these `BepInEx` files automatically generated after first start of the game, I suppose that BepInEx was improperly installed.

If in the log console it says that you have 0 plugins that means the BepInEx version is wrong.

I haven't seen any other issues with the mod yet.
