### ISSUE TITLE
Installation problems involving thunderstore

### ISSUE THREAD

**Issue by WindyJellyfish** [limtis0/SkulPatcher#4]
so I downloaded the mod with thunderstore mod manager and added bepinexpack with it too, but the mod menu wont start up despite everything, even typing f7 repeatedly does nothing, how to fix this?

**Comment by limtis0** [comment]
Hello,

Sorry, for the inconvenience. Right now Thunderstore modloader is not working with Skul.
Right now we are waiting for this update to be merged: https://github.com/ebkr/r2modmanPlus/pull/1001

For now, the only way is to go with the manual installation process.
I will update the README

**Comment by WindyJellyfish** [comment]
I see, thanks for the heads up, I tried manual too and it worked worse, so I'll just wait (some error code relating to steam).

**Comment by limtis0** [comment]
> I see, thanks for the heads up, I tried manual too and it worked worse, so I'll just wait (some error code relating to steam).

If you are talking about the error-code in a command line window: this error code seems to be thrown because of the game's "anti-piracy" system.
This one should not prevent your game from starting correctly.
If command line is not showing, you must locate BepInEx folder in your game files and set the config to show the debug console.
Just check whether BepInEx tells you that "X plugins were found" or something like this. Also, look out for other errors.
If it does not see the plugins, check whether BepInEx version is correct. IIRC it should be 5.4.21

...Or you can just wait for the modloader, but these guys are quite slow, so it may take a week or so...

**Comment by WindyJellyfish** [comment]
a week? I can wait for that.
